user:
  #experiment_dir: /scratch2/BMC/fv3lam/MPAS_stoch/expt_dirs/test_stoch_global
  experiment_dir: /scratch2/BMC/fv3lam/Gerard.Ketefian/tmp/expt_dirs/global_01
  platform: hera
  mesh_label: x1.40962

data:
  mesh_files: /scratch2/BMC/fv3lam/mayfield/mpas_stoch/meshes/120km-global

platform:
  account: fv3lam

workflow:
  tasks:
    task_get_ics_data: !remove
    task_get_lbcs_data: !remove
    task_ungrib:
      dependency: !remove

prepare_grib:
  ungrib:
    gfs_files:
      path: "/scratch2/BMC/fv3lam/MPAS_stoch/icbc_data/GFS/gfs.t{cycle_hour:02d}z.pgrb2.0p25.f{forecast_hour:03d}"

create_ics:
  mpas_init: &mpas_init_config
    boundary_conditions:
      length: 12
    execution:
      batchargs:
        cores: 128
        walltime: 02:30:00
      mpiargs:
        - "--ntasks={{ create_ics.mpas_init['execution']['batchargs']['cores']}}"
    namelist:
      base_file: "{{ user.mpas_app }}/src/MPAS-Model/namelist.init_atmosphere"
      update_values: &mpas_init_update_values
        data_sources:
          config_fg_interval: !int "{{ create_ics.mpas_init['boundary_conditions']['interval_hours'] * 3600 }}"
        vertical_grid:
          config_blend_bdy_terrain: false

create_lbcs:
  mpas_init:
    boundary_conditions: 
      length: 12

forecast:
  mpas:
    execution:
      batchargs:
        cores: 128
        walltime: 02:30:00
        partition: 'hera'
    length: 12
    namelist:
      base_file: "{{ user.mpas_app }}/src/MPAS-Model/namelist.atmosphere"
      update_values:
        nhyd_model:
          config_dt: 60.0
        limited_area:
          config_apply_lbcs: false
    streams:
#      path: "{{ user.mpas_app }}/parm/streams.atmosphere.IN"
#      values:
#        output_interval: 01:00:00
#    files_to_copy:
#      stream_list.atmosphere.diagnostics: "{{ user.mpas_app }}/src/MPAS-Model/stream_list.atmosphere.diagnostics"
#      stream_list.atmosphere.output: "{{ user.mpas_app }}/src/MPAS-Model/stream_list.atmosphere.output"
#      stream_list.atmosphere.surface: "{{ user.mpas_app }}/src/MPAS-Model/stream_list.atmosphere.surface"
      output:
        mutable: true
        type: output
        filename_template: "history.$Y-$M-$D_$h.$m.$s.nc"
        output_interval: "01:00:00"
        files:
          - stream_list.atmosphere.output
        clobber_mode: overwrite
      diagnostics:
        mutable: true
        type: output
        filename_template: "diag.$Y-$M-$D_$h.$m.$s.nc"
        output_interval: "01:00:00"
        files:
          - stream_list.atmosphere.diagnostics
        clobber_mode: overwrite
#      surface:
#        mutable: true
#        type: input
#        filename_template: "x1.40962.sfc_update.nc"
#        io_type: "pnetcdf,cdf5"
#        filename_interval: "none"
#        input_interval: "none"
#        files:
#          - stream_list.atmosphere.surface
