
forecast:
  mpas:
    namelist:
      update_values:
        nam_stochy:
          do_sppt: true
          config_spptint: 0
          config_sppt_1: 0.8
          config_sppt_2: 0.4
          config_sppt_3: 0.1
          config_sppt_tau_1: 21600
          config_sppt_tau_2: 86400
          config_sppt_tau_3: 21600
          config_sppt_lscale_1: 500000
          config_sppt_lscale_2: 1000000
          config_sppt_lscale_3: 2000000
          config_sppt_logit: true
          config_sppt_sfclimit: true
          # The 'str:' at the beginning of these is needed so that experiment_gen.py
          # doesn't automatically convert these two integers; they need to be passed
          # as strings in the final namelist.
          config_iseed_sppt1: 'str:2026010112001'
          config_iseed_sppt2: 'str:0'
          config_iseed_sppt3: 'str:0'
          config_sppt_hgt_top1: 15000
          config_sppt_hgt_top2: 27000
          config_stochini: false
