
forecast:
  mpas:
    namelist:
      update_values:
        nam_stochy:
          do_sppt: true
          config_sppt_2: 0.0
          config_sppt_3: 0.0
          config_sppt_lscale_1: 50000
          config_spptint: 600.0
