user:
  expt_basedir:

forecast:
  mpas:
    execution:
      batchargs:
        cores:
    length:
    namelist:
      update_values:
        nhyd_model:
          config_dt:
        nam_stochy:
          do_sppt:
          config_spptint:
          config_sppt_2: 0.0
          config_sppt_3: 0.0
          config_sppt_lscale_1:
